name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - dev
      - staging
      - production

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  # test-migrations:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3