name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - dev
      - staging
      - production

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  test-migrations:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Migrate Up 1
      run: docker run -v $PWD/migrations:/migrations --network host migrate/migrate -path=/migrations/ -database postgres://localhost:5432/database up
    # - name: Migrate Down 1
    #   run: 
    # - name: Migrate Up 2
    #   run: 
